version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/new_chatapp
  - source: /gunicorn.services
    destination: /etc/systemd/system/
  - source: /fundoo.conf
    destination: /etc/nginx/sites-available/
hooks: 
  BeforeInstall:
    - location: /beforeinstallation.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /afterinstallation.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: /stop_server.sh
      timeout: 300
      runas: root
